swagger: "2.0"
info:
  description: Complete API Document
  version: "1.0.0"
  title: Scribe Web REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

paths:
  /hello:
    get:
      x-swagger-router-controller: Scribe.api.hello
      operationId: "get"
      tags:
        - "Testing"
      summary: "List devices in Scribe database"
      description: "Successfully loaded api"
      responses:
        200:
          description: "Successfully loaded api"
          schema:
            type: "array"
            items:
              properties:
                Message:
                  type: "string"
