image: "alpine:latest"

before_script:
  - apk add --no-cache python3 gcc python3-dev musl-dev linux-headers libffi-dev make alpine-sdk openssl-dev
  - python3 -m venv env
  - source ./env/bin/activate
  - pip3 install -r requirements.txt

Coverage:
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - source ./env/bin/activate
    - python -m unittest discover
    - coverage report -m
    - coverage-badge
