image: "alpine:latest"

before_script:
  - apk add --no-cache python3
  - python3 -m venv env
  - source ./env/bin/activate
  - pip3 install -r requirements.txt

build:
<<<<<<< HEAD
  script:
    - source ./env/bin/activate
    - python3 ./web_app.py
=======
  - source ./env/bin/activate
  - python3 ./web_appy.py
>>>>>>> a2386db7f1813e518172fd716c2989115b065010
