"""First Migration

Revision ID: 70aa9c60d7a4
Revises: 
Create Date: 2020-03-05 22:27:02.940304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70aa9c60d7a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_associations',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=120), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['devices.alias'], ),
    sa.ForeignKeyConstraint(['group'], ['groups.groupname'], ),
    sa.ForeignKeyConstraint(['user'], ['users.username'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.drop_table('remote_repos')
    op.add_column('device_models', sa.Column('os', sa.String(length=120), nullable=False))
    op.drop_column('device_models', 'OS')
    op.alter_column('devices', 'alias',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('devices', 'port',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(22)'))
    op.alter_column('devices', 'user',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'devices', ['ip'])
    op.create_unique_constraint(None, 'devices', ['port'])
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'proxies', ['proxy'], ['alias'])
    op.create_foreign_key(None, 'devices', 'repos', ['repo'], ['repo_name'])
    op.drop_column('devices', 'username')
    op.create_unique_constraint(None, 'groups', ['groupname'])
    op.add_column('proxies', sa.Column('alias', sa.String(length=120), nullable=False))
    op.alter_column('proxies', 'port',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(22)'))
    op.create_unique_constraint(None, 'proxies', ['alias'])
    op.create_unique_constraint(None, 'repos', ['repo_name'])
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['password_hash'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'groups', ['group'], ['groupname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'groups', ['group'], ['pk'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'repos', type_='unique')
    op.drop_constraint(None, 'proxies', type_='unique')
    op.alter_column('proxies', 'port',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(22)'))
    op.drop_column('proxies', 'alias')
    op.drop_constraint(None, 'groups', type_='unique')
    op.add_column('devices', sa.Column('username', sa.TEXT(), nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'repos', ['repo'], ['pk'])
    op.create_foreign_key(None, 'devices', 'proxies', ['proxy'], ['pk'])
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.alter_column('devices', 'user',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('devices', 'port',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(22)'))
    op.alter_column('devices', 'alias',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('device_models', sa.Column('OS', sa.TEXT(), nullable=True))
    op.drop_column('device_models', 'os')
    op.create_table('remote_repos',
    sa.Column('pk', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('URL', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['repos.name'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.drop_table('device_associations')
    # ### end Alembic commands ###
