"""empty message

Revision ID: 7b8c99223d51
Revises: c0c0d8c8863f
Create Date: 2021-04-11 00:30:40.105418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b8c99223d51"
down_revision = "c0c0d8c8863f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_associations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "group")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("group", sa.VARCHAR(length=64), nullable=True))
    op.create_foreign_key(None, "users", "groups", ["group"], ["groupname"])
    op.drop_table("group__associations")
    # ### end Alembic commands ###
