swagger: "2.0"
info:
  description: Complete API Document
  version: "1.0.0"
  title: Scribe Web REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  /nodes:
    get:
      x-swagger-router-controller: api.devices
      operationId: "get"
      tags:
        - "Devices"
      summary: "List devices in Scribe database"
      description: "Pulls all devices found in the Scribe database and returns them. The device name
      must always be an ip, this is due to how LibreNMS request devices from Scribe. To combat the previous
      issue alias has been added as a sort of \"human readable\" name."
      responses:
        200:
          description: "Successfully pulled device list from sqlite db"
          schema:
            type: "array"
            items:
              properties:
                alias:
                  type: "string"
                enabled:
                  type: "string"
                ip:
                  type: "string"
                model:
                  type: "string"
                port:
                  type: "string"

  /node/:
    post:
      x-swagger-router-controller: api.devices
      operationId: "add"
      tags:
        - "Devices"
      summary: "Add a device to Scribe database"
      description: "A nodes to Scribe DB"
      parameters:
        - name: node
          in: body
          description: Used to add a node to Scribe db
          schema:
            type: object
            properties:
              ip:
                type: "string"
              port:
                type: "integer"
                description: "Defaults to port 22 if not provided"
              alias:
                type: "string"
              model:
                type: "integer"
              username:
                type: "string"
              password:
                type: "string"
              enable:
                type: "string"
                description: "Defaults to no enable if not provided"
              enabled:
                type: "boolean"
                description: "defaults to True if not provided"
            required:
              - ip
              - alias
              - model
              - username
              - password
      responses:
        201:
          description: Successfully added node to Scribe db
        406:
          description: Database error

  /node/{ip}:
    delete:
      x-swagger-router-controller: api.devices
      operationId: "delete"
      tags:
        - "Devices"
      summary: "Remove a device from Scribe db"
      description: Remove a node from db via ip address
      parameters:
        - name: ip
          in: path
          type: string
          required: True
          description: This should always be the IP of the device to be added
      responses:
        201:
          description: Successfully added node to Scribe db
        406:
          description: Database error

  /node/fetch/{ip}:
    get:
      x-swagger-router-controller: api.devices
      operationId: "fetch"
      tags:
        - "Devices"
        - "Oxidized Compatible"
      summary: "Used to get node config"
      description: "When provided an ip this will spit out the last known config"
      parameters:
        - name: ip
          in: path
          type: string
          required: True
          description: This should always be the IP of the device to be added
      produces:
        - text/plain; charset=utf-8
      responses:
        200:
          description: "Successfully pulled device list from sqlite db"
          schema:
            type: "string"

  /node/purge/{ip}:
    delete:
      x-swagger-router-controller: api.devices
      operationId: "purge"
      tags:
        - "Devices"
      summary: "Remove a device from Scribe db"
      description: Remove a node from db via ip address
      parameters:
        - name: ip
          in: path
          type: string
          required: True
          description: This should always be the IP of the device to be added
      responses:
        201:
          description: Successfully added node to Scribe db
        406:
          description: Database error

  /node/disable/{ip}:
    put:
      x-swagger-router-controller: api.devices
      operationId: "disable"
      tags:
        - "Devices"
      summary: "Disable a device in scribe"
      description: Disable a device in scribe, this does not remove it from the database or FS
      parameters:
        - name: ip
          in: path
          type: string
          required: True
      responses:
        201:
          description: Successfully disabled node in Scribe db

  /node/enable/{ip}:
    put:
      x-swagger-router-controller: api.devices
      operationId: "enable"
      tags:
        - "Devices"
      summary: "Enable a device in scribe"
      description: Enable a device in scribe
      parameters:
        - name: ip
          in: path
          type: string
          required: True
      responses:
        201:
          description: Successfully enabled node in Scribe db    

  /users:
    get:
      x-swagger-router-controller: api.users
      operationId: "get"
      tags:
        - "Users"
      summary: "List users in Scribe db"
      description: "List all users available in the Scribe db. A user in here is a group in LibreNMS"
      responses:
        200:
          description: "Successfully pulled user list from db"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: string
  /user/{user}:
    parameters:
      - in: path
        name: user
        type: string
        required: true
        description: The user name
    post:
      x-swagger-router-controller: api.users
      operationId: "add"
      tags:
        - "Users"
      summary: Add a user to Scribe db
      responses:
        201:
          description: Successfully added user to Scribe db
        406:
          description: user already exists in Scribe db
    delete:
      x-swagger-router-controller: api.users
      operationId: "delete"
      tags:
        - "Users"
      summary: Remove a user from Scribe db
      responses:
        201:
          description: Successfully removed user to Scribe db

  /models:
    get:
      x-swagger-router-controller: api.models
      operationId: "get"
      tags:
        - "Models"
      summary: "List models in Scribe db"
      description: "List all models available in the Scribe db."
      responses:
        200:
          description: "Successfully pulled model list from db"
          schema:
            type: "array"
            items:
              properties:
                OS:
                  type: string
                manufacturer:
                  type: string
                model:
                  type: string
                pk:
                  type: integer

  /model/:
    post:
      x-swagger-router-controller: api.models
      operationId: "add"
      tags:
        - "Models"
      summary: Add a model to Scribe db
      parameters:
        - name: model
          in: body
          schema:
            type: object
            properties:
              manufacturer:
                type: string
              model:
                type: string
              OS:
                type: string
      responses:
        201:
          description: Successfully added model to Scribe db
        406:
          description: Model already exists in Scribe db

  /model/{pk}:
    delete:
      x-swagger-router-controller: api.models
      operationId: "delete"
      tags:
        - "Models"
      summary: Remove a model from Scribe db
      parameters:
        - name: pk
          in: path
          type: string
          required: True
          description: This should always be the id of the model to be removed
      responses:
        201:
          description: Successfully removed model to Scribe db

  /model/{ip}:
    parameters:
      - in: path
        name: ip
        type: string
        required: true
        description: The model name (think OS name)
    get:
      x-swagger-router-controller: api.models
      operationId: "get_devices_model"
      tags:
        - "Models"
      summary: Get the model of a device by its IP
      responses:
        200:
          description: "Successfully pulled model list from db"
          schema:
            type: "array"
            items:
              properties:
                OS:
                  type: string
                manufacturer:
                  type: string
                model:
                  type: string
